
TMA =load('/Users/alexandonian/heterogeneity/breast_cancer_tma/src/mat_files/StructData_CC_Pheno.mat');

TMA.base_path = '/Users/alexandonian/heterogeneity/breast_cancer_tma/';
TMA.paths = {'/Users/alexandonian/heterogeneity/breast_cancer_tma/images/ER-allTissue/',...
    '/Users/alexandonian/heterogeneity/breast_cancer_tma/images/ER-myadj/';...
    '/Users/alexandonian/heterogeneity/breast_cancer_tma/images/PR-allTissue/',...
    '/Users/alexandonian/heterogeneity/breast_cancer_tma/images/PR-myadj/';...
    '/Users/alexandonian/heterogeneity/breast_cancer_tma/images/HER2-allTissue/',...
    '/Users/alexandonian/heterogeneity/breast_cancer_tma/images/HER2-myadj/'};

    
    